// <auto-generated />
using System;
using FiloTakipWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiloTakipWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707135723_AddUpdatedAtToArac")]
    partial class AddUpdatedAtToArac
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelKm")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SasiNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YakitTipi")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Plaka")
                        .IsUnique();

                    b.HasIndex("SubeId");

                    b.ToTable("Araclar", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.AracSoforAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoforId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("SoforId");

                    b.ToTable("AracSoforAtamalari", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<bool>("ArizaKaydiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("BakimTipi")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KmOkumasi")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaliyetToplam")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServisAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SonrakiBakimKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonrakiBakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("BakimKayitlari", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimMasrafi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BakimKaydiId")
                        .HasColumnType("int");

                    b.Property<string>("MasrafKategorisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BakimKaydiId");

                    b.ToTable("BakimMasraflari", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimParcaDegisimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("BakimKaydiId")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParcaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToplamFiyat")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BakimKaydiId");

                    b.ToTable("BakimParcaDegisimleri", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Belge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("BelgeAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BelgeTipi")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosyaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UyariBildirimMi")
                        .HasColumnType("bit");

                    b.Property<int?>("UyariGunSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("Belgeler", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BildirimSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("IcerikSablonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OlayTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BildirimSablonlari", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.CezaIhlalKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("CezaTuru")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OdenmisMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoforId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("SoforId");

                    b.ToTable("CezaIhlalKayitlari", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("SubeId");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.MasrafKategorisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MasrafKategorileri", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Sefer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("BaslangicNoktasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durumu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GercekBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GercekBitis")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GercekKm")
                        .HasColumnType("int");

                    b.Property<string>("IrsaliyeNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnaylandiMi")
                        .HasColumnType("bit");

                    b.Property<int?>("OnaylayanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlanlananBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanlananBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanlananKm")
                        .HasColumnType("int");

                    b.Property<string>("RedGerekce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeferBelgesiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoforId")
                        .HasColumnType("int");

                    b.Property<string>("VarisNoktasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("YolcuBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YukBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("SoforId");

                    b.ToTable("Seferler", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.SigortaPolicesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosyaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Prim")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SigortaSirketi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SigortaTuru")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("SigortaPoliceleri", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Sofor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EhliyetGecerlilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EhliyetNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EhliyetSinifi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PerformansPuani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoforDurumu")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TcNo")
                        .IsUnique();

                    b.ToTable("Soforler", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Sehir")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subeler", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.YakitGirisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnormalTuketimMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IstasyonAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KmOkumasi")
                        .HasColumnType("int");

                    b.Property<decimal>("Litre")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Litreper100Km")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("PompaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoforId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("YakitKartiNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YakitTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("SoforId");

                    b.ToTable("YakitGirisleri", (string)null);
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Arac", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Sube", "Sube")
                        .WithMany("Araclar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.AracSoforAtama", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany("AracSoforAtamalari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiloTakipWebApi.Models.Entities.Sofor", "Sofor")
                        .WithMany("AracSoforAtamalari")
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimKaydi", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimMasrafi", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.BakimKaydi", "BakimKaydi")
                        .WithMany("Masraflar")
                        .HasForeignKey("BakimKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimKaydi");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimParcaDegisimi", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.BakimKaydi", "BakimKaydi")
                        .WithMany("ParcaDegisimleri")
                        .HasForeignKey("BakimKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimKaydi");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Belge", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany("Belgeler")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.CezaIhlalKaydi", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany()
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FiloTakipWebApi.Models.Entities.Sofor", "Sofor")
                        .WithMany("CezaIhlalKayitlari")
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Kullanici", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Sube", "Sube")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Sefer", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany("Seferler")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiloTakipWebApi.Models.Entities.Sofor", "Sofor")
                        .WithMany("Seferler")
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.SigortaPolicesi", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany("SigortaPoliceleri")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.YakitGirisi", b =>
                {
                    b.HasOne("FiloTakipWebApi.Models.Entities.Arac", "Arac")
                        .WithMany("YakitGirisleri")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiloTakipWebApi.Models.Entities.Sofor", "Sofor")
                        .WithMany()
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Arac");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Arac", b =>
                {
                    b.Navigation("AracSoforAtamalari");

                    b.Navigation("BakimKayitlari");

                    b.Navigation("Belgeler");

                    b.Navigation("Seferler");

                    b.Navigation("SigortaPoliceleri");

                    b.Navigation("YakitGirisleri");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.BakimKaydi", b =>
                {
                    b.Navigation("Masraflar");

                    b.Navigation("ParcaDegisimleri");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Sofor", b =>
                {
                    b.Navigation("AracSoforAtamalari");

                    b.Navigation("CezaIhlalKayitlari");

                    b.Navigation("Seferler");
                });

            modelBuilder.Entity("FiloTakipWebApi.Models.Entities.Sube", b =>
                {
                    b.Navigation("Araclar");

                    b.Navigation("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
